// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Delete(arg1:number):Promise<models.Process>;

export function DeleteHistory():Promise<boolean>;

export function GetAll():Promise<Array<models.Process>>;

export function OpenVideo(arg1:string):Promise<boolean>;

export function OutputFile(arg1:string):Promise<boolean>;

export function Start(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<boolean>;

export function Upload(arg1:string,arg2:string,arg3:string):Promise<{[key: string]: any}>;
