// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAll():Promise<Array<models.Process>>;

export function Upload(arg1:string,arg2:string):Promise<{[key: string]: any}>;
