// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAll() {
  return window['go']['controllers']['ConversionController']['GetAll']();
}

export function Upload(arg1, arg2) {
  return window['go']['controllers']['ConversionController']['Upload'](arg1, arg2);
}
