// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['controllers']['ConversionController']['Delete'](arg1);
}

export function DeleteHistory() {
  return window['go']['controllers']['ConversionController']['DeleteHistory']();
}

export function GetAll() {
  return window['go']['controllers']['ConversionController']['GetAll']();
}

export function OpenVideo(arg1) {
  return window['go']['controllers']['ConversionController']['OpenVideo'](arg1);
}

export function OutputFile(arg1) {
  return window['go']['controllers']['ConversionController']['OutputFile'](arg1);
}

export function Start(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['controllers']['ConversionController']['Start'](arg1, arg2, arg3, arg4, arg5);
}

export function Upload(arg1, arg2, arg3) {
  return window['go']['controllers']['ConversionController']['Upload'](arg1, arg2, arg3);
}
